import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const OvoFont = Ovo({
  subsets: ["latin"],
  weight: ["400"]
});


export const metadata = {
  title: "Blissan Studio - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${OvoFont.className} antialiased leading-8
        overflow-x-hidden`}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
